target_os = "win"
target_cpu = "x64"
is_component_build = false
is_debug = false
use_custom_libcxx = false
v8_monolithic = true
v8_static_library = true
v8_enable_disassembler = true
v8_enable_object_print = true
v8_use_external_startup_data = false
dcheck_always_on = false
symbol_level = 0
is_clang = true
v8_enable_pointer_compression = false
treat_warnings_as_errors = false
extra_cflags = [
  "-D_SILENCE_CXX20_OLD_SHARED_PTR_ATOMIC_SUPPORT_DEPRECATION_WARNING",
  "-D_SILENCE_ALL_CXX20_DEPRECATION_WARNINGS",
  "-Wno-deprecated-declarations",
]
extra_cxxflags = [
  "-D_SILENCE_CXX20_OLD_SHARED_PTR_ATOMIC_SUPPORT_DEPRECATION_WARNING",
  "-D_SILENCE_ALL_CXX20_DEPRECATION_WARNINGS",
  "-Wno-deprecated-declarations",
]
